"""empty message

Revision ID: 23833d608093
Revises: 6e0c80827435
Create Date: 2020-03-30 19:16:37.859467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23833d608093'
down_revision = '6e0c80827435'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('start_time', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Show', 'start_time')
    # ### end Alembic commands ###
